### ISSUE TITLE
word wrap throws an exception if the regex doesn't match anything on line 24

### ISSUE THREAD

**Issue by toddself** [jonschlinkert/word-wrap#3]
input: `\r\n` returns:
↳ npm test

> word-wrap@1.0.0 test /Users/todd/src/scripto2/node_modules/word-wrap
> mocha -R spec

  wrap
    ✓ should use defaults to wrap words in the given string:
    ✓ should wrap to the specified width:
    ✓ should indent the specified amount:
    ✓ should use the given string for newlines:
    ✓ should trim trailing whitespace:
    1) should handle strings with just newlines

  5 passing (9ms)
  1 failing

  1) wrap should handle strings with just newlines:
     TypeError: Cannot read property 'join' of null
      at module.exports (/Users/todd/src/scripto2/node_modules/word-wrap/index.js:25:35)
      at Context.<anonymous> (/Users/todd/src/scripto2/node_modules/word-wrap/test.js:38:5)
      at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

**Comment by jonschlinkert** [comment]
thanks for the fix! I published a 1.0.1 version to npm. I think this is the last package I published in December right before my pc died, so there was a version mismatch between what is on github and npm, but it's now fixed.

**Comment by toddself** [comment]
Awesome thanks so much!

**Comment by jonschlinkert** [comment]
anytime, thanks for the PR!
